# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- develop

name: 0.0.0$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore Exemplum.sln  
  displayName: 'Restore'
  
- script: dotnet build Exemplum.sln --configuration $(buildConfiguration)  
  displayName: 'Build'
