name: Publish Exemplum Template to nuget
on:
  push:
    branches: [ main ]
    paths:
      - 'Exemplum.nuspec'
jobs:
  publish:
    name: list on nuget
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - name: Package the template
        run: nuget pack Exemplum.nuspec

      - name: Publish to nuget.org
        run: nuget push Exemplum.Template.*.nupkg -src https://api.nuget.org/v3/index.json ${{secrets.NUGET_API_KEY}}